### ISSUE TITLE
Use Touch Display on first Bootup over GPIO per default

### ISSUE THREAD

**Issue by Cryptec** [Raspihive/raspihive#2]
we should enable the output on the GPIO Display per default, cause its easyer for people to set up, and no external monitor is required then. 

I think the best is to install necessary drivers and do system changes before the initial setup automatically. 
Some simple commands should be enough: 

`sudo rm -rf LCD-show`
`git clone https://github.com/goodtft/LCD-show.git`
`chmod -R 755 LCD-show`
`cd LCD-show`
`sudo ./LCD35-show`

but we have to test tis solution. Would be great to hear feedback.

**Comment by Cryptec** [comment]
is it possible to use Both, GPIO and USB to display the same?

**Comment by PIOTA89** [comment]
just use touch display with micro hdmi port...
