### ISSUE TITLE
GUI Window to set the Dashboard password. 

### ISSUE THREAD

**Issue by Cryptec** [Raspihive/raspihive#25]
At the moment, we have to add the Passwort for the Dasboard Login in the commandline. This have to be changed to GUI. Otherwise we have the need of a Commandline, although our motto is "a Plug and Play Node without the need of a commandline".

Also, if we provide a ready to go image, which boots directly in Fullscreen Hive, there is no option to see or enter the Commandline at the insallation Process.

**Comment by PIOTA89** [comment]
Already integrated.
