### ISSUE TITLE
Menu icons not displaying

### ISSUE THREAD

**Issue by anistark** [Raspihive/raspihive#38]
**Describe the bug**
Menu icons are not displaying.
Probably an image path issue.

**Expected behavior**
Menu icons should be visible.

**Screenshots**
![Screenshot from 2021-01-23 19-37-13](https://user-images.githubusercontent.com/5357586/105580620-73bb6480-5d5b-11eb-83af-8c61d61575a7.png)

**Desktop (please complete the following information):**
 - OS: Fedora release 33 (Thirty Three)
 - Version 8.13

**Comment by PIOTA89** [comment]
It works now ;)
